### ISSUE TITLE
proxyMiddleware?

### ISSUE THREAD

**Issue by tetiogit** [AYCRAL/meteor-router-stardust#1]
I've seen this line in some repos, but I don't understand the meaning...

WebApp.rawConnectHandlers.use(proxyMiddleware(`http://localhost:${GRAPHQL_PORT}/graphql`));

Where this webapp is referenced to? and what is the use of proxymiddleware?
Thanks

**Comment by cristiandley** [comment]
Hi @tetiogit 

I know, by default meteor exports WebApp so you dont have to import it... i should import it (*fix*)

```proxymiddleware``` encapsulates my custom port of ```graphql``` into meteors 3000 port
