### ISSUE TITLE
Upgrade example to work with React Router 4?

### ISSUE THREAD

**Issue by joshterrill** [AYCRAL/meteor-router-stardust#2]
The react-router team has made a pretty huge change in their API from versions 2/ 3 to 4. A lot of people are already starting to use v4 and I think it'd be awesom if this project used it to: https://github.com/ReactTraining/react-router/tree/v4

Here's an FAQ on what the difference is: https://github.com/ReactTraining/react-router/blob/v4/README.md#v4-faq

Edit: this might be something I can do a pull request for if you want me to.

**Comment by cristiandley** [comment]
hey @joshterrill !!! its cool to see that people get interest on this examples !!! 👍 

Im working right now on a new example `CONTACT - FORM + VIEW FOR THE INPUTS` i will be really happy if you do a pull request !!!!.

**Comment by joshterrill** [comment]
@cristiandley I was thinking about upgrading a few things in this to more closely mimic how the react meteor guide is laid out. i.e. moving js files to jsx files, having the export on the same line as the class definition, etc. What do you think? I can probably get to it by mid-week.

**Comment by cristiandley** [comment]
@joshterrill !!! :smiley: that sounds awesome !! I like your idea... you seem to be a cool guy !! im also trying to make some other open source tutorials. I hate the community that grow up around meteor like `meteorpedia` or stuff like that... people need to learn for free. And most free resources out there are just very simple examples that dont solve the doubts.

Im looking for help, i you have time contact me!

_Things im working now_:

 - [How to deploy meteor](https://github.com/AYCRAL/meteor-deployment)  (this need to be improved a lot)

 - Working also on `how to configure NGINX`... (working mainly on how to use SUBPATHS on it and not only the common response "better go with subdomains")

 - and... on some on a simple app called `Contact Me` that is a complete example using Meteor + Apollo
